### PR TITLE
Set the user agent for web view

### PR DESCRIPTION
**Pull request by timbielawski**
In response to  - Android 403: Error: Disallowed Useragent #87

Need to set the user agent get around the 403

### CODE REVIEW

**Comment by auser** [comment]
Thanks for the PR!

**Comment by maslianok** [comment]
@auser @acco Can we publish this to npm?

**Comment by auser** [comment]
Yep! I will push this tonight!

**Comment by Jazz747** [comment]
Is this merged with master?

**Comment by roshangm1** [comment]
Hi This make issue loading the desktop version facebook screen which makes it ugly. any way to show the mobile version of the page with these changes ?

**Comment by roshangm1** [comment]
https://github.com/fullstackreact/react-native-oauth/pull/130
I made a pull request that fixes this issue as well as opens mobile version of facebook.
My forked repo:
https://github.com/roshangm1/react-native-oauth/

**Pull request merged**
