### PR TITLE
Remove deprecated createJSModules @Override

### PR DESCRIPTION
**Pull request by piuholo**
Breaking changes in React Native 0.47

facebook/react-native@ce6fb33

### CODE REVIEW

**Comment by tallen11** [comment]
Should you get rid of the entire method, not just the override directive?

**Comment by piuholo** [comment]
If you remove the entire method instead of the _@Override_ , backwards compatibility is lost.

**Comment by jesster2k10** [comment]
Just a side note, the package.json still needs to be updated but a workaround would be loading the package from git opposed to the NPM repository

**Comment by vbuch** [comment]
@auser could you please push the npm version? And maybe make sure package.json and npm version match?

**Pull request merged**
