### PR TITLE
Fixes for Twitter and Google login on Android

### PR DESCRIPTION
**Pull request by gvillenave**

### CODE REVIEW

**Comment by kyle-ssg** [comment]
Any chance of this getting merged ? Android twitter auth basically doesn't work without this from what I can see.

**Comment by stewartlord** [comment]
👍 this should be merged!

**Comment by hanalaydrus** [comment]
@gvillenave would you mind to fix the conflicts? I hope this will be merged after the conflicts solve.

**Comment by gvillenave** [comment]
Done!

**Comment by f4z3k4s** [comment]
This definitely should be merged. Although, line 410: `String oauthTokenSecret = (String) accessTokenMap.get("oauth_token_secret");` in `android/src/main/java/io/fullstack/oauth/OAuthManagerModule.java` should also be dealt with. It casues me a build error(`error: cannot find symbol` pointing to this line) in case of android release builds, rebased to package version 2.2.0. Apart from that, Twitter finally redirects me to my app. Thanks.

**Comment by desktp** [comment]
This also fixes crashing on logging in with GitHub. +1 for merging!

**Comment by joncursi** [comment]
The only issue I see with this is that the location of the `authorized` key is different on iOS than android. On iOS, you have to check:

```
if (accessTokenData.response.authorized)
```

whereas on android, you have to use:

```
if (accessTokenData.authorized)
```

The API should be the same across these platforms.

**Review by SailingSteve — COMMENTED** [review]
Line 410 of OAuthManagerModule needs to be changed to 
String oauthTokenSecret = (String) accessToken.getParameter("token_secret");

It is working for me on Android after that one change.

**Comment by MBach** [comment]
Nice catch @SailingSteve 
This PR should really be merged into master!

**Comment by developersoul** [comment]
Please merge this package, or maybe if you doesn't has the time to maintain this package pass it to some one how can like react-native-community or some contributor... Thanks for all the effort. I said cause I doesn't seem changes for 4 months ago.

**Comment by monolithed** [comment]
Why did you remove these lines? 

```java
Map accessTokenMap = new Gson().fromJson(accessToken.getRawResponse(), Map.class);
```

**Comment by negebauer** [comment]
This should also be deleted

https://github.com/gvillenave/react-native-oauth/blob/4f34e87e99863ba04fe0a11646712ef2b16a28f2/android/src/main/java/io/fullstack/oauth/OAuthManagerModule.java#L410

And also this

https://github.com/gvillenave/react-native-oauth/blob/4f34e87e99863ba04fe0a11646712ef2b16a28f2/android/src/main/java/io/fullstack/oauth/OAuthManagerModule.java#L421

**Pull request closed without merging**
